Disease-Prediction-using-Django-and-machine-learning-master/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [


    path('sign_in_admin', views.sign_in_admin , name='sign_in_admin'),

    path('signup_patient', views.signup_patient, name="signup_patient"),
    path('sign_in_patient', views.sign_in_patient , name='sign_in_patient'),
    path('savepdata/<str:patientusername>', views.savepdata , name='savepdata'),
    

    path('signup_doctor', views.signup_doctor , name="signup_doctor"),
    path('sign_in_doctor', views.sign_in_doctor , name='sign_in_doctor'),
    path('saveddata/<str:doctorusername>', views.saveddata , name='saveddata'),

    path('logout', views.logout , name='logout'),
]

Disease-Prediction-using-Django-and-machine-learning-master/disease_prediction/urls.py
from django.urls import path,include

urlpatterns = [
     path("", include("main_app.urls")),
     path("accounts/", include("accounts.urls")),
]

Disease-Prediction-using-Django-and-machine-learning-master/main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField

from datetime import date

# Create your models here.


#user = models.OneToOneField(settings.AUTH_USER_MODEL)

class patient(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    
    is_patient = models.BooleanField(default=True)
    is_doctor = models.BooleanField(default=False)

    name = models.CharField(max_length = 50)
    dob = models.DateField()
    address = models.CharField(max_length = 100)
    mobile_no = models.CharField(max_length = 15)
    gender = models.CharField(max_length = 10)

    
    @property
    def age(self):
        today = date.today()
        db = self.dob
        age = today.year - db.year
        if today.month < db.month or today.month == db.month and today.day < db.day:
            age -= 1
        return age 



class doctor(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    is_patient = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=True)

    name = models.CharField(max_length = 50)
    dob = models.DateField()
    address = models.CharField(max_length = 100)
    mobile_no = models.CharField(max_length = 15)
    gender = models.CharField(max_length = 10)

    registration_no = models.CharField(max_length = 20)
    year_of_registration = models.DateField()
    qualification = models.CharField(max_length = 20)
    State_Medical_Council = models.CharField(max_length = 30)

    specialization = models.CharField(max_length = 30)

    rating = models.IntegerField(default=0)
    image=models.ImageField(null=True, blank=True, upload_to="media")
    image_data = models.BinaryField(null=True)

class diseaseinfo(models.Model):

    patient = models.ForeignKey(patient , null=True, on_delete=models.SET_NULL)

    diseasename = models.CharField(max_length = 200)
    no_of_symp = models.IntegerField()
    symptomsname = ArrayField(models.CharField(max_length=200))
    confidence = models.DecimalField(max_digits=5, decimal_places=2)
    consultdoctor = models.CharField(max_length = 200)

Disease-Prediction-using-Django-and-machine-learning-master/templates/patient/view_profile/view_profile.html
{% extends "basic.html" %}
{% load static %}

 
	{% block head %}


  <link rel="stylesheet" href="{% static 'patient/view_profile/forms.css' %}">
  <link rel="stylesheet" href="{% static 'patient/view_profile/responsive.css' %}">
  <link rel="stylesheet" href="{% static 'patient/view_profile/base.css' %}">



{% endblock %}




{% block body %}


    <!-- Content -->
    <div id="content" class="colM">
        
        <div id="content-main">

<fieldset class="module aligned ">

<div class="border border-dark rounded-lg mx-auto mt-3 " style="width:600px">

    <div class="container mt-3 "  >
        
          <div class="mx-auto text-center"><h2 >          Patient Profile - {{ puser.patient.name }} </h2> 
          </div>



  
   <div class="form-row field-username">


       <div>
                  
             <label class="required" for="id_username">username:</label>
                      
                   <input type="text" name="username" value={{puser.username}} class="vTextField" maxlength="50" required="" id="id_username">
                      
                  
                  
              </div>
          
          </div>

          

<div class="form-row field-name">


  <div>
      
      
          <label class="required" for="id_name">Name:</label>
          
              <input type="text" name="name" value={{puser.patient.name}} class="vTextField" maxlength="50" required="" id="id_name">
          
      
      
  </div>

</div>


<div class="form-row field-email">


    <div>
        
        
            <label class="required" for="id_email">Email:</label>
            
                <input type="text" name="email" value={{puser.email}} class="vTextField" maxlength="100" required="" id="id_email">
            
        
        
    </div>

</div>


<div class="form-row field-dob">


  <div>
      
      
          <label class="required" for="id_dob">Dob:</label>
          
              <input type="text" name="dob" value={{puser.patient.dob|date:'Y-m-d'}} class="vDateField" size="10" required="" id="id_dob">
              
</div>
</div>

<div class="form-row field-address">


  <div>
      
      
          <label class="required" for="id_address">Address:</label>
          
              <input type="text" name="address" value={{puser.patient.address}} class="vTextField" maxlength="100" required="" id="id_address">
          
      
      
  </div>

</div>

<div class="form-row field-mobile_no">


  <div>
      
      
          <label class="required" for="id_mobile_no">Mobile no:</label>
          
              <input type="text" name="mobile_no" value={{puser.patient.mobile_no}} class="vTextField" maxlength="15" required="" id="id_mobile_no">
          
      
      
  </div>

</div>

<div class="form-row field-gender">


  <div>
      
      
          <label class="required" for="id_gender">Gender:</label>
          
              <input type="text" name="gender" value={{puser.patient.gender}} class="vTextField" maxlength="10" required="" id="id_gender">
          
      
      
  </div>

</div>

</div>

{% if request.user.patient %}

            <div class="comtainer mt-3 mb-3 ml-4 mr-4">
              
                <div class="btn-group">
                  <button type="button" class="btn btn-secondary pr-4 pl-4 mr-5 ml-5 " data-toggle="collapse" data-target="#save">Edit</button>
                  <div id="save" class="collapse ml-5 mr-5">
                    <button type="button"  id="save" class="btn btn-success pr-4 pl-4 mr-5 ml-5 ">Save</button>
                    </div>
                 
                </div>
                
            </div>
      {% endif %}



</div>

</fieldset>
      
 </div>
    <!-- END Content -->

</div>
<!-- END Container -->



<script>

  $(document).ready( function(){
    $('#save').click( function(event){

    dob = document.getElementById('id_dob').value,
    

    $.ajax({
        url :"{% url 'savepdata' puser.username %}",
        type : "POST",
        data : { 

        'csrfmiddlewaretoken': '{{ csrf_token }}',
        "name" :document.getElementById('id_name').value,
        "dob" :dob,
        "gender" :document.getElementById('id_gender').value,
        "address" :document.getElementById('id_address').value,
        "mobile_no" :document.getElementById('id_mobile_no').value

       },

        success : function(){
          alert("new data is saved.")
        }

    });


  });
});

</script>


{% endblock %}